blog/urls.py
from django.urls import  path
from .views import BlogListView,BlogCreateViews,BlogDetailView,BlogUpdateView,BlogDeleteView

app_name = "blog"

urlpatterns = [
    path('',BlogListView.as_view(),name='home'),
    path('create/',BlogCreateViews.as_view(),name='create'),
    path('<int:pk>/',BlogDetailView.as_view(),name='detail'),
    path('<int:pk>/update/',BlogUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/',BlogDeleteView.as_view(),name='delete')
]

core/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include
from .views import HomeViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeViews.as_view(),name='home'),
    path('blog/',include('blog.urls'),name='blog'),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()

    def __str__(self):
        return self.title
    

blog/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import View,UpdateView,DeleteView
from .form import PostCreateForm
from .models import Post
# Create your views here.
class BlogListView(View):
    def get(self,req,*args,**kwargs):
        posts=Post.objects.all()
        context={
            'posts':posts
        }
        return render(req,'blog_list_index.html',context)

class BlogCreateViews(View):
    def get(self,req,*args,**kwargs):
        form=PostCreateForm()
        context={
            'form':form
        }
        return render(req,'blog_create.html',context)

    def post(self,req,*args,**kwargs):
        if req.method == "POST":
            form=PostCreateForm(req.POST)
            if form.is_valid():
                title=form.cleaned_data.get('title')
                content=form.cleaned_data.get('content')

                p,created=Post.objects.get_or_create(title=title,content=content)
                p.save()
                return redirect('blog:home')

        context={
        }
        return render(req,'blog_create.html',context)

class BlogDetailView(View):
    def get(self,req,pk,*args,**kwargs):
        post=get_object_or_404(Post,pk=pk)
        context={
            'post':post
        }
        return render(req,'blog_datail.html',context)

class BlogUpdateView(UpdateView):
    model=Post
    fields=['title','content']
    template_name='blog_update.html'

    def get_success_url(self):
        pk=self.kwargs['pk']
        return reverse_lazy('blog:detail',kwargs={'pk':pk})

class BlogDeleteView(DeleteView):
    model=Post
    template_name='blog_delete.html'
    success_url=reverse_lazy('blog:home')

core/views.py
from django.shortcuts import render
from django.views.generic import View

class HomeViews(View):
    def get(self,req,*args,**kwargs):
        context={

        }
        return render(req,'index.html',context)

templates/blog_create.html
<form method='POST'>
    {% csrf_token %}
    title{{form.title}}
    </br>
    content{{form.content}}
    <button type='submit'>Sumit</button>
</form>

templates/blog_datail.html
<h2>Detail</h2></br>
{{post.title}}</br>
{{post.content}}</br>
<a href="{% url 'blog:home' %}">home</a></br>

templates/blog_delete.html
Are you Sure?
<form method='POST'>
    {% csrf_token %}
    {{form}}
    <button type='submit'>Delete</button>
</form>

templates/blog_list_index.html
<h1>blog list </h1></br>
    {% for  post in posts  %}
    <a href="{% url 'blog:detail' post.id %}">{{post.title}}</a></br>
    {{post.content}}</br>
    <a href="{% url 'blog:update' post.id %}">update</a></br>
    <a href="{% url 'blog:delete' post.id %}">Delete</a></br>
    
{% endfor %}
</br>
<a href='{% url 'blog:create' %}'>create </a>

templates/blog_update.html
<form method='POST'>
    {% csrf_token %}
    title{{form.title}}
    </br>
    content{{form.content}}
    <button type='submit'>Save</button>
</form>

templates/index.html
<h1>Hola desde template </h1><br>
<h2>Visita mi blog</h2><br>
<a href="{% url 'blog:home' %}">Aqui mi blog</a>